use serde::{Deserialize, Serialize};

/// A registered SQL Sentinel node (one per PC / server)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SentinelNode {
    #[serde(default)]          // generated by the hub on POST /nodes
    pub id:          String,
    pub name:        String,   // e.g. "warehouse-pc", "erp-server"
    pub url:         String,   // e.g. "http://192.168.1.20:2020"
    pub description: String,
    pub active:      bool,
}

/// Lightweight status returned after pinging a node
#[derive(Debug, Serialize, Deserialize)]
pub struct NodeHealth {
    pub node_id: String,
    pub online:  bool,
    pub latency_ms: Option<u64>,
}
